### PR TITLE
Add support for guard

### PR DESCRIPTION
**Pull request by dhoppe**
Hello, 

I am a huge fan of the Chef cookbooks, generated with the gem 'knife-skeleton'. Please merge this pull request to add the support for guard.

Kind regards, Dennis

### CODE REVIEW

**Comment by Sliim** [comment]
Hello @dhoppe, 

thanks for your contribution! Looks good for me, can you just add the `guard` gem package in the generated Gemfile? From the guard's readme:
```
group :development do
  gem 'guard'
end
```
Thanks

**Comment by dhoppe** [comment]
Hello @Sliim, 

no problem. Somehow this file went missing. It should have been part of my first commit :(

Kind regards, Dennis

**Comment by Sliim** [comment]
Cool, it's ok for me :+1: 
@PierreRambaud can you review this and merge if it's good for you? Thanks

**Comment by dhoppe** [comment]
Hello @Sliim / @PierreRambaud, 

I just added a small commit to ignore the project directory of RubyMine and all other IDE's from JetBrains. 

Kind regards, Dennis

**Comment by Sliim** [comment]
:+1:

**Comment by PierreRambaud** [comment]
Thanks a lot ;)

**Comment by PierreRambaud** [comment]
I push a new version on rubygems.

**Pull request merged**
